config/routes.rb
Rails.application.routes.draw do

	#HP側
	root to: "home#top"
	get "about" => "home#about"
	get "kodawari" => "home#kodawari"
	get "store" => "home#store"
	get "menus" => "home#menus"
	resources :notices, only: [:index,:show]
	resources :reservations, only: [:show,:create,:new,:destroy]
	post "/reservations/confirm"  => "reservations#confirm"
	post "/reservations/new"=> "reservations#back"
	get "delete"=> "reservations#delete"
	get 'ajax', to: 'reservations#ajax'

	 ##管理者側
  	devise_for :admins, skip: :all
  	#ログイン画面制限
	devise_scope :admin do
	  get 'login' => 'devise/sessions#new', as: :new_admin_session
	  post 'login' => 'devise/sessions#create', as: :admin_session
	  delete 'logout' => 'devise/sessions#destroy', as: :destroy_admin_session
	end

	# ゲストログイン用URL
	devise_scope :admin do
	    post 'admins/guest_sign_in', to: 'admins/sessions#new_guest'
	end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	namespace :admin do
	  resources :notices
	  resources :reservations
	  get 'ajax', to: 'reservations#ajax'
	  root to: "home#about"
	end
end

app/models/reservation.rb
class Reservation < ApplicationRecord

	validates :customer_name, presence: true,length: {maximum: 20}
	validates :people, presence: true
	validates :reservation_time, presence: true
	validates :reservation_day, presence: true
	validates :phone_number, presence: true,length: { minimum: 10, maximum: 11 }

	#Eメール
	#英数字、アンダースコア (_)、プラス (+)、ハイフン (-)、ドット (.) のいずれかを少なくとも1文字以上繰り返す
	#+アットマーク,英小文字、数字、ハイフン、ドットのいずれかを少なくとも1文字以上繰り返す
	#+ドット,英小文字を少なくとも1文字以上繰り返す,大文字小文字を無視するオプション
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email,presence: true,format: {with: VALID_EMAIL_REGEX, allow_blank: true}

    #予約機能検索
	scope :search_date, -> (date) { where(reservation_day: date) }
	scope :lunch, -> { where("reservation_time < 4") }
	scope :dinner, -> { where("reservation_time > 3") }

	#予約機能
	enum people: %i[1 2 3 4 5 6 7 8 9 10]
	enum reservation_time: %i[11:00 12:00 13:00 14:00 17:00 18:00 19:00 20:00 21:00]
end

app/controllers/admin/reservations_controller.rb
class Admin::ReservationsController < ApplicationController

	before_action :authenticate_admin!

	before_action :set_reservation, only: [:new,:create]
	before_action :find_reservation, only: [:show,:edit,:destroy,:update]

	def index
		if params[:link] == "new"
			#新着予約
	    	@reservations = Reservation.where(created_at: Time.now.all_day).order(:reservation_day).page(params[:page]).per(10)
	    elsif params[:link] == "today"
	    	#本日の予約
	       	@reservations = Reservation.where(reservation_day: Date.today).order(:reservation_time).page(params[:page]).per(10)
	    else
	    	#過去の予約を非表示
	    	@reservations = Reservation.where.not("reservation_day < ?", Date.today).order(:reservation_day)
	    	#予約検索
	    	@reservations = @reservations.search_date(params[:search_date])if params[:search_date].present?
	    	@reservations = @reservations.lunch if params[:reservation_type] == 'lunch'
	    	@reservations = @reservations.dinner if params[:reservation_type] == 'dinner'
	    	#並びかえ
			@reservations = @reservations.order(:reservation_time).page(params[:page]).per(10)
			#検索後の表示指定
			@search_time = params[:reservation_type]
			@search_day = params[:search_date]
	    end
	    #予約0件時のアラート
	    @reservation = @reservations.count
    	if @reservation == 0
    		flash.now[:alert] = "予約はありません！"
		end
	    #新着予約　件数バッジ
	    @reservations_new_badge = Reservation.where(created_at: Time.now.all_day).order(:reservation_day)
	    @reservation_new_badge = @reservations_new_badge.count
	    #本日の予約　件数バッジ
	    @reservations_today_badge = Reservation.where(reservation_day: Date.today).order(:reservation_time)
	    @reservation_today_badge = @reservations_today_badge.count

	    #予約全部　件数バッジ
	    @reservations_all_badge = Reservation.where.not("reservation_day < ?", Date.today).order(:reservation_day)
	    @reservation_all_badge = @reservations_all_badge.count
	end

	def new
		@reservation = Reservation.new
	end

	def show
	end

	def edit
	end

	def create
		@reservation = Reservation.new(reservation_params)
		#予約人数確認
		reservations = Reservation.where(reservation_day: @reservation.reservation_day).where(reservation_time: @reservation.reservation_time)
		a = 0
		reservations.each do |reservation|
			a += reservation.people.to_i
		end
		#合計10人以下
		if a + @reservation.people.to_i <= 10

			if @reservation.save
				redirect_to admin_reservation_path(@reservation.id)
			else
				render 'new'
			end
		else
			if 10 - a < 1
				flash.now[:alert] = "ご希望の日時ですとご予約は満席となります！"
				render 'new'
			else
				flash.now[:alert] = "ご希望の日時ですと予約可能人数は#{10-a}名までとなります！"
				render 'new'
			end
		end
	end

	def destroy
	    @reservation.destroy
	    redirect_to admin_reservations_path
	end

	def update
		#予約人数確認
		reservations = Reservation.where(reservation_day: @reservation.reservation_day).where(reservation_time: @reservation.reservation_time)
		a = 0
		reservations.each do |reservation|
			a += reservation.people.to_i
		end
		a -= @reservation.people.to_i
		#合計10人以下
		if a + reservation_params[:people].to_i <= 10

			if @reservation.update(reservation_params)
				redirect_to admin_reservation_path(@reservation.id)
			else
				render 'edit'
			end
		else
			if 10 - a < 1
				flash.now[:alert] = "ご希望の日時ですとご予約は満席となります！"
				render 'edit'
			else
				flash.now[:alert] = "ご希望の日時ですと予約可能人数は#{10-a}名までとなります！"
				render 'edit'
			end
		end
	end

	def ajax
		#変数に選ばれたデータを入れる
		@reservation = Reservation.new(reservation_day:params[:reservation_day], reservation_time:params[:reservation_time],people:params[:people])
		#人数を絞る
		reservation_peoples = Reservation.where(reservation_day:params[:reservation_day]).where(reservation_time:params[:reservation_time])
		a = 0
		reservation_peoples.each do |reservation|
			a += reservation.people.to_i
		end
		a = 10 - a
		@peoples = Reservation.people.first(a).map{ |k,v| [k, v + 1] }

		#時間帯を絞る
		reservation_times = Reservation.where(reservation_day:params[:reservation_day])
		reservation_times1 = reservation_times.where(reservation_time:"11:00")
		b = params[:people].to_i
		reservation_times1.each do |reservation|
			b += reservation.people.to_i
		end

		reservation_times2 = reservation_times.where(reservation_time:"12:00")
		c = params[:people].to_i
		reservation_times2.each do |reservation|
			c += reservation.people.to_i
		end

		reservation_times3 = reservation_times.where(reservation_time:"13:00")
		d = params[:people].to_i
		reservation_times3.each do |reservation|
			d += reservation.people.to_i
		end

		reservation_times4 = reservation_times.where(reservation_time:"14:00")
		e = params[:people].to_i
		reservation_times4.each do |reservation|
			e += reservation.people.to_i
		end

		reservation_times5 = reservation_times.where(reservation_time:"17:00")
		f = params[:people].to_i
		reservation_times5.each do |reservation|
			f += reservation.people.to_i
		end

		reservation_times6 = reservation_times.where(reservation_time:"18:00")
		g = params[:people].to_i
		reservation_times6.each do |reservation|
			g += reservation.people.to_i
		end

		reservation_times7 = reservation_times.where(reservation_time:"19:00")
		h = params[:people].to_i
		reservation_times7.each do |reservation|
			h += reservation.people.to_i
		end

		reservation_times8 = reservation_times.where(reservation_time:"20:00")
		i = params[:people].to_i
		reservation_times8.each do |reservation|
			i += reservation.people.to_i
		end

		reservation_times9 = reservation_times.where(reservation_time:"21:00")
		j = params[:people].to_i
		reservation_times9.each do |reservation|
			j += reservation.people.to_i
		end

		if b < 11
			b = "11:00"
		else
			b = 11
		end

		if c < 11
			c = "12:00"
		else
			c = 11
		end

		if d < 11
			d = "13:00"
		else
			d = 11
		end

		if e < 11
			e = "14:00"
		else
			e = 11
		end

		if f < 11
			f = "17:00"
		else
			f = 11
		end

		if g < 11
			g = "18:00"
		else
			g = 11
		end

		if h < 11
			h = "19:00"
		else
			h = 11
		end

		if i < 11
			i = "20:00"
		else
			i = 11
		end

		if j < 11
			j = "21:00"
		else
			j = 11
		end

		@reservation_times = Reservation.reservation_times.slice(b,c,d,e,f,g,h,i,j).keys
	end

	private

	def reservation_params
	    params.require(:reservation).permit(:customer_name,:people,:reservation_time,:reservation_day,:phone_number,:email,:request)
	end

	def set_reservation
		@peoples = Reservation.people.keys
		@reservation_times = Reservation.reservation_times.keys
	end

	def find_reservation
		@reservation = Reservation.find(params[:id])
	end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

	before_action :set_reservation, only: [:new,:create,:confirm,:back]
	before_action :new_reservation, only: [:create,:confirm,:back]
	before_action :find_reservation, only: [:show,:destroy]

	def new
		@reservation = Reservation.new
	end

	def show
	end

	def create
		#予約人数確認
		reservations = Reservation.where(reservation_day: @reservation.reservation_day).where(reservation_time: @reservation.reservation_time)
		a = 0
		reservations.each do |reservation|
			a += reservation.people.to_i
		end
		#合計10人以下
		if a + @reservation.people.to_i <= 10

			if params[:back]
	      		render 'new'
			elsif @reservation.save
				redirect_to reservation_path(@reservation.id)
			else
				render 'new'
			end
		else
			if 10 - a < 1
				flash.now[:alert] = "ご希望の日時ですとご予約は満席となります！"
				render 'new'
			else
				flash.now[:alert] = "ご希望の日時ですと予約可能人数は#{10-a}名までとなります！"
				render 'new'
			end
		end
	end

	def destroy
	    @reservation.destroy
	    redirect_to delete_path
	end

	def delete
	end

	def confirm
  		render "new" if @reservation.invalid?
	end

	def back
    	render "new"
    end

	def ajax
		#変数に選ばれたデータを入れる
		@reservation = Reservation.new(reservation_day:params[:reservation_day], reservation_time:params[:reservation_time],people:params[:people])
		#人数を絞る
		reservation_peoples = Reservation.where(reservation_day:params[:reservation_day]).where(reservation_time:params[:reservation_time])
		a = 0
		reservation_peoples.each do |reservation|
			a += reservation.people.to_i
		end
		a = 10 - a
		@peoples = Reservation.people.first(a).map{ |k,v| [k, v + 1] }

		#時間帯を絞る
		reservation_times = Reservation.where(reservation_day:params[:reservation_day])
		reservation_times1 = reservation_times.where(reservation_time:"11:00")
		b = params[:people].to_i
		reservation_times1.each do |reservation|
			b += reservation.people.to_i
		end

		reservation_times2 = reservation_times.where(reservation_time:"12:00")
		c = params[:people].to_i
		reservation_times2.each do |reservation|
			c += reservation.people.to_i
		end

		reservation_times3 = reservation_times.where(reservation_time:"13:00")
		d = params[:people].to_i
		reservation_times3.each do |reservation|
			d += reservation.people.to_i
		end

		reservation_times4 = reservation_times.where(reservation_time:"14:00")
		e = params[:people].to_i
		reservation_times4.each do |reservation|
			e += reservation.people.to_i
		end

		reservation_times5 = reservation_times.where(reservation_time:"17:00")
		f = params[:people].to_i
		reservation_times5.each do |reservation|
			f += reservation.people.to_i
		end

		reservation_times6 = reservation_times.where(reservation_time:"18:00")
		g = params[:people].to_i
		reservation_times6.each do |reservation|
			g += reservation.people.to_i
		end

		reservation_times7 = reservation_times.where(reservation_time:"19:00")
		h = params[:people].to_i
		reservation_times7.each do |reservation|
			h += reservation.people.to_i
		end

		reservation_times8 = reservation_times.where(reservation_time:"20:00")
		i = params[:people].to_i
		reservation_times8.each do |reservation|
			i += reservation.people.to_i
		end

		reservation_times9 = reservation_times.where(reservation_time:"21:00")
		j = params[:people].to_i
		reservation_times9.each do |reservation|
			j += reservation.people.to_i
		end

		if b < 11
			b = "11:00"
		else
			b = 11
		end

		if c < 11
			c = "12:00"
		else
			c = 11
		end

		if d < 11
			d = "13:00"
		else
			d = 11
		end

		if e < 11
			e = "14:00"
		else
			e = 11
		end

		if f < 11
			f = "17:00"
		else
			f = 11
		end

		if g < 11
			g = "18:00"
		else
			g = 11
		end

		if h < 11
			h = "19:00"
		else
			h = 11
		end

		if i < 11
			i = "20:00"
		else
			i = 11
		end

		if j < 11
			j = "21:00"
		else
			j = 11
		end

		@reservation_times = Reservation.reservation_times.slice(b,c,d,e,f,g,h,i,j).keys
	end

	private

	def reservation_params
	    params.require(:reservation).permit(:customer_name,:people,:reservation_time,:reservation_day,:phone_number,:email,:request)
	end

	def set_reservation
		@peoples = Reservation.people.keys
		@reservation_times = Reservation.reservation_times.keys
	end

	def new_reservation
		@reservation = Reservation.new(reservation_params)
	end

	def find_reservation
		@reservation = Reservation.find(params[:id])
	end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/admin/reservations/_select_admin_reservation.html.erb
<%= form_for(@reservation, url:admin_reservations_path) do |f| %>
	<% if @reservation.errors.any? %>
      <div id="error_explanation">
        <font color = "red">
          <h3>入力した内容に<%= @reservation.errors.count %>件のエラーがあります</h3>
          <ul>
          <% @reservation.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </font>
      </div>
    <% end %>
    <div>
      	<h4 id="alert" style="color:red;"><%= alert %></h4>
    </div>
	<h4>予約日<span class="label label-warning pull-right">必須</span></h4>

	<%= f.text_field :reservation_day,id: "reservation_day", readonly: true,placeholder: 'カレンダーの日付をタップしてください',style: "width:100%;" %>

	<h4>予約時間<span class="label label-warning pull-right">必須</span></h4>

	<h5>*日時と人数で予約可能時間帯が絞られます。</h5>

	<%= f.select :reservation_time,@reservation_times,id: "reservation_time" %>

	<h4>予約人数<span class="label label-warning pull-right">必須</span></h4>

	<h5>*日時と時間帯で予約可能人数が絞られます。</h5>

	<%= f.select :people,@peoples, id: "people" %>

	<h4>名前<span class="label label-warning pull-right">必須</span></h4>
	<%= f.text_field :customer_name,style: "width:100%",placeholder: '20文字以内で入力'%>

	<h4>電話番号<span class="label label-warning pull-right">必須</span></h4>
	<%= f.text_field :phone_number,style: "width:100%",placeholder: '10〜11桁の数字のみ入力'%>

	<h4>メールアドレス<span class="label label-warning pull-right">必須</span></h4>
	<%= f.text_field :email,style: "width:100%",placeholder: '途中に@と.を必ず入れて入力'%>

	<h4>ご要望</h4>
	<%= f.text_area :request,style: "width:100%",rows:"5"%>

	<%= f.submit "予約状況を確認します", class: "btn btn-primary" %>
<% end %>

<!-- 予約機能入力入力欄 -->
<script type="text/javascript">
// 日付
$('#reservation_reservation_time').on('click', function() {
	$('#reservation_people').on('click', function() {
  		var input_day = $("#reservation_day").val();
  		var input_time = $("#reservation_reservation_time").val();
  		console.log(input_day, input_time)
  		$.ajax({
	    url: "/admin/ajax",
	    type: "GET",
	    data:{
	    	reservation_day: input_day,
	    	reservation_time: input_time,
	    	}
	    });
	});
});
// 時間
$('#reservation_people').on('click', function() {
$('#reservation_reservation_time').on('click', function() {
		var input_day = $("#reservation_day").val();
		var input_people = $("#reservation_people").val();
		console.log(input_day, input_people)
		$.ajax({
	    url: "/admin/ajax",
	    type: "GET",
	    data:{
	    	reservation_day: input_day,
	    	people: input_people,
	    	}
	    });
    });
});
// 人数
$('#calendar').on('click', function() {
	var input_day = $("#reservation_day").val();
	console.log(input_day)
	$.ajax({
	    url: "/admin/ajax",
	    type: "GET",
	    data:{
	    	reservation_day: input_day,
	    	}
	    });
});
</script>

app/views/admin/reservations/ajax.js.erb
 $('.select_reservation').html('<%= escape_javascript(render partial: "admin/reservations/select_admin_reservation",reservation_people:@peoples,reservation:@reservation,reservation_reservation_time:@reservation_times) %>')

app/views/admin/reservations/edit.html.erb
<div class="container-fluid background-image2">
	<div class="row">
	    <h2 class="reservation-title"><span class="border">予約編集</span></h2>
	    <div class="col-xs-2"></div>
	    <div class="col-xs-4">
	    	<div id="calendar"></div>
      		<h4>＊<span style ="color:red;">赤色</span>は定休日になります</h4>
	    </div>
	      	<div class="col-xs-4"style="padding-bottom:20px;">
		        <%= form_for(@reservation, url:admin_reservation_path) do |f| %>
		        <% if @reservation.errors.any? %>
		          <div id="error_explanation">
		            <font color = "red">
		              <h3>入力した内容に<%= @reservation.errors.count %>件のエラーがあります</h3>
		              <ul>
		              <% @reservation.errors.full_messages.each do |message| %>
		                <li><%= message %></li>
		              <% end %>
		              </ul>
		            </font>
		          </div>
		        <% end %>
		        <div>
			      	<h4 id="alert" style="color:red;"><%= alert %></h4>
			    </div>
  				<h4>予約日<span class="label label-warning pull-right">必須</span></h4>
  				<%= f.text_field :reservation_day, id: "reservation_day",readonly: true,placeholder: 'カレンダーの日付をタップしてください',style: "width:100%;" %>

  				<h4>予約時間<span class="label label-warning pull-right">必須</span></h4>
	  			<%= f.select :reservation_time, [["11:00", "11:00"], ["12:00","12:00"], ["13:00","13:00"], ["14:00","14:00"], ["17:00", "17:00"],["18:00","18:00"],["19:00","19:00"],["20:00","20:00"],["21:00","21:00"]],class:"form-control" %>

	  			<h4>予約人数<span class="label label-warning pull-right">必須</span></h4>
	  			<%= f.select :people, [["1", 1], ["2", 2], ["3", 3], ["4", 4], ["5", 5], ["6", 6], ["7", 7], ["8", 8], ["9", 9], ["10", 10]] ,class:"form-control" %>

	  			<h4>名前<span class="label label-warning pull-right">必須</span></h4>
	  			<%= f.text_field :customer_name,style: "width:100%",placeholder: '20文字以内で入力'%>

	  			<h4>電話番号<span class="label label-warning pull-right">必須</span></h4>
	  			<%= f.text_field :phone_number,style: "width:100%",placeholder: '10〜11桁の数字のみ入力' %>

	  			<h4>メールアドレス<span class="label label-warning pull-right">必須</span></h4>
	  			<%= f.text_field :email,style: "width:100%",placeholder: '途中に@と.を必ず入れて入力'%>

	  			<h4>ご要望</h4>
	  			<%= f.text_area :request,style: "width:100%",rows:"5"%>

	  			<div class="btn-group btn-group-justified" style="padding-top: 20px;">
		            <div class="btn-group">
		              <%= f.submit "編集完了", class: "btn btn-warning" %>
		            </div>
		            <div class="btn-group">
		              <%= link_to admin_reservation_path(@reservation.id),method: :get do %>
		                <button class="btn btn-success">詳細に戻る</button>
		              <% end %>
		            </div>
		        </div>
		  	<% end %>
		  	</div>
	    <div class="col-xs-2"></div>
	</div>
</div>
<!-- カレンダー機能 -->
<script type="text/javascript" charset="utf-8">
$(document).ready(function(){
	$('#calendar').fullCalendar({
	  	dayClick: function(date, jsEvent, view) {
		    $(this).on('click', function(){
	    	    if($(this).hasClass('fc-past')){
   				 }else{
	    	    if($(this).hasClass('fc-sun')){
   				 }else{
		    	//クリックした日付が取れる
	    		$('#reservation_day').val(date.format());
	    		//選択状態だった場合クラスを削除する
		        $('td').removeClass('selected-date');
		        $('td').removeClass('fc-today');
		        //クリックされたtdに選択状態クラスを追加(addClass)する
		        $(this).addClass('selected-date');
		    	}
		    	}
		    });
	  	}
	});
});
</script>

app/views/admin/reservations/index.html.erb
<div class="container-fluid background-image2">
	<div class="row">
		<h2 class="reservation-title"><span class ="border">築地寿司の予約</span></h2>
		<div class="col-xs-1"></div>
		<div class="col-xs-4">
			<div class="calendar"id="calendar"></div>
			<h4>＊<span style ="color:red;">赤色</span>は定休日になります</h4>
		</div>
		<div class="col-xs-6">
  			<div class="btn-group btn-group-justified" >
  				<div class="btn-group">
			  		<%= link_to admin_reservations_path(link: "new") do %>
		            	<button class="btn btn-default">新着予約　<span class="badge"><%= @reservation_new_badge%></span></button>
		          	<% end %>
		        </div>
		        <div class="btn-group">
		          	<%= link_to admin_reservations_path(link: "today") do %>
		            	<button class="btn btn-default">本日予約　<span class="badge"><%= @reservation_today_badge%></span></button>
		          	<% end %>
		        </div>
		        <div class="btn-group">
		          	<%= link_to admin_reservations_path do %>
		            	<button class="btn btn-default">予約全部　<span class="badge"><%= @reservation_all_badge%></span></button>
		          	<% end %>
		        </div>
	        </div>
        	<h3 style="margin:15px 0;">検索機能</h3>
          	<%= form_tag(admin_reservations_path,:method => 'get') do %>
		        <div class="col-xs-5"style="padding:0;">
		        	<!-- *text_field_tag(要素名 [, 値, オプション]) -->
		            <%= text_field_tag :search_date, @search_day, id: "reservation_day",readonly: true,placeholder: 'カレンダーの日付をタップしてください', class:"reservation-from" %>
		        </div>
		        <div class="col-xs-2"style="padding:0;">
		            <%= select_tag :reservation_type,options_for_select([["1日", ""],["ランチ", "lunch"],["ディナー","dinner"]], selected: @search_time),class:"reservation-from"%>
		        </div>
		        <div class="col-xs-2"style="padding:0;">
		            <button type="submit" class="btn btn-default reservation-from">検索する</button>
		        </div>
	        <% end %>
	        <div class="col-xs-3"style="padding:0;">
		        <%= link_to new_admin_reservation_path do %>
	            	<button class="btn btn-primary pull-right reservation-from">予約追加</button>
	          	<% end %>
	        </div>
	  		<table class="table reservation-table-border"style="padding-top:10px;">
	  			<thead>
					<tr class="active">
						<th>予約日</th>
						<th>予約時間</th>
						<th>お名前</th>
						<th>人数</th>
						<th>ご要望</th>
						<th></th>
						<th></th>
					</tr>
				</thead>
	            <tbody>
	              <% @reservations.each do |reservation| %>
	              <tr class="reservation-table-font">
	              	<td><%= reservation.reservation_day.strftime("%Y/%m/%d")%></td>
	                <td><%= reservation.reservation_time%></td>
	                <td><%= reservation.customer_name.truncate(10) + "様"%></td>
	                <td><%= reservation.people%>人</td>
	                <%if reservation.request.present? %>
	                <td><span style ="color:red;">有り</span></td>
	                <% else %>
	                <td></td>
	                <% end %>
	                <td>
                  		<%= link_to admin_reservation_path(reservation.id) do %>
	                    	<button class="btn btn-success">詳細</button>
	                  	<% end %>
	                </td>
	                <td>
	                  	<%= link_to admin_reservation_path(reservation.id),method: :delete, data: {confirm: '削除しますか？'} do %>
	                    	<button class="btn btn-danger">削除</button>
	                  	<% end %>
	                </td>
	              </tr>
	              <% end %>
	            </tbody>
	        </table>
        	<h4 id="alert"><%= alert %></h4>
	        <div  class="kaminari">
	            <%= paginate @reservations %>
	        </div>
	    </div>
	    <div class="col-xs-1"></div>
	</div>
</div>
<!-- カレンダー機能 -->
<script type="text/javascript" charset="utf-8">
$(document).ready(function(){
	$('#calendar').fullCalendar({
	  	dayClick: function(date, jsEvent, view) {
		    $(this).on('click', function(){
		    	if($(this).hasClass('fc-past')){
   				 }else{
	    	    if($(this).hasClass('fc-sun')){
   				 }else{
		    	//クリックした日付が取れる
	    		$('#reservation_day').val(date.format());
	    		//選択状態だった場合クラスを削除する
		        $('td').removeClass('selected-date');
		        $('td').removeClass('fc-today');
		        //クリックされたtdに選択状態クラスを追加(addClass)する
		        $(this).addClass('selected-date');
		    	}
		    	}
		    });
	  	}
	});
});
</script>

app/views/admin/reservations/show.html.erb
<div class="container-fluid background-image2">
	<div class="row">
	    <h2 class="reservation-title"><span class="border">予約詳細</span></h2>
	    <div class="col-xs-4"></div>
	      	<div class="col-xs-4"style="padding-bottom:20px;">
		        <table class="table reservation-table">
					<tbody>
						<tr>
							<th width="40%">予約日時</th>
							<td width="60%"><%= @reservation.reservation_day.strftime("%Y/%m/%d") %></td>
						</tr>
						<tr>
							<th>予約時間</th>
							<td><%= @reservation.reservation_time %></td>
						</tr>
						<tr>
							<th>予約人数</th>
							<td><%= @reservation.people %>人</td>
						</tr>
						<tr>
							<th>名前</th>
							<td><%= @reservation.customer_name + "様" %></td>
						</tr>
						<tr>
							<th>電話番号</th>
							<td><%= @reservation.phone_number %></td>
						</tr>
						<tr>
							<th>メールアドレス</th>
							<td><%= @reservation.email %></td>
						</tr>
						<tr>
							<th>ご要望</th>
							<td class="reservation-request"><%= @reservation.request %></td>
						</tr>
					</tbody>
				</table>
				<div class="btn-group btn-group-justified" >
		            <div class="btn-group">
		              <%= link_to edit_admin_reservation_path(@reservation.id) do %>
		                <button class="btn btn-warning">編集する</button>
		              <% end %>
		            </div>
		            <div class="btn-group">
		              <%= link_to admin_reservations_path do %>
		                <button class="btn btn-default">一覧に戻る</button>
		              <% end %>
		            </div>
		            <div class="btn-group">
		              <%= link_to admin_reservation_path(@reservation.id), method: :delete, data: {confirm: 'キャンセルしますか？'} do %>
	                    <button class="btn btn-danger">キャンセルする</button>
	                <% end %>
		            </div>
		        </div>
		    </div>
	    <div class="col-xs-4"></div>
	</div>
</div>