config/routes.rb
Rails.application.routes.draw do

	#HP側
	root to: "home#top"
	get "about" => "home#about"
	get "kodawari" => "home#kodawari"
	get "store" => "home#store"
	get "menus" => "home#menus"
	resources :notices, only: [:index,:show]
	resources :reservations, only: [:show,:create,:new,:destroy]
	post "/reservations/confirm"  => "reservations#confirm"
	post "/reservations/new"=> "reservations#back"
	get "delete"=> "reservations#delete"
	get 'ajax', to: 'reservations#ajax'

	 ##管理者側
  	devise_for :admins, skip: :all
  	#ログイン画面制限
	devise_scope :admin do
	  get 'login' => 'devise/sessions#new', as: :new_admin_session
	  post 'login' => 'devise/sessions#create', as: :admin_session
	  delete 'logout' => 'devise/sessions#destroy', as: :destroy_admin_session
	end

	# ゲストログイン用URL
	devise_scope :admin do
	    post 'admins/guest_sign_in', to: 'admins/sessions#new_guest'
	end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	namespace :admin do
	  resources :notices
	  resources :reservations
	  get 'ajax', to: 'reservations#ajax'
	  root to: "home#about"
	end
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < ApplicationController
	before_action :authenticate_admin!

	def about
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def top
		@notices = Notice.order(created_at: :desc).first(8)
	end

	def about
	end

	def store
	end

	def menus
	end

	def kodawari
	end

end

app/views/home/about.html.erb
<div class="container-fluid background-image2">
	<div class="row" style="text-align: center;padding: 30px 0;">
		<h2><span class="border">ネット予約について</span></h2>
		<h4 style="padding: 20px 0;">↓築地寿司の予約は以下の手順で行われます↓</h4>
		<div class="col-xs-0 col-lg-2"></div>
		<div class="col-xs-12 col-lg-8">
			<div class="col-xs-12 col-lg-4 about-resp box1">
				<h3>STEP1</h3>
				<%= image_tag 'image14.jpg',size:'250x150',class: ''%>
				<h4 class="about-font">予約したい日付・時間帯・人数を選んで入力し、その際、選ばれた日付に応じて予約可能な時間帯と人数は絞られて表示されます。</h4>
			</div>
			<div class="col-xs-12 col-lg-4 about-resp box2">
				<h3>STEP２</h3>
				<%= image_tag 'image12.jpg',size:'250x150',class: ''%>
				<h4 class="about-font">その他に名前、電話番号、メールアドレスを入力し確認ボタンを押してください。＊記念日やアレルギーなどについてはご要望欄にてお願いします。</h4>
			</div>
			<div class="col-xs-12 col-lg-4 about-resp box3">
				<h3>STEP３</h3>
				<%= image_tag 'image13.jpg',size:'250x150',class: ''%>
				<h4 class="about-font">入力確認画面にて入力内容を確認し、予約を確定してください。</h4>
			</div>
		</div>
		<div class="col-xs-0 col-lg-2"></div>
	</div>
</div>

app/views/home/kodawari.html.erb
<div class="container background-image2">
	<div class="row">
		<div class="kodawari-title">
			<h1 class="kodawari-title-font">こだわり</h1>
		</div>
	</div>
	<div class="row">
		<div class="col-xs-12 col-lg-6 "style="padding:20px 0; text-align: center;">
			<h1 class="kodawari-font2"><%= image_tag 'logo.png',size:'40x40',class: 'kodawari-logo'%>仕入れのこだわり</h1>
			<h3 class="kodawari-font">世界最大の魚市場、</h3>
			<h3 class="kodawari-font">東京中央卸売市場に築地寿司はこだわります。</h3>
			<h3 class="kodawari-font">日本各地から集まった一級品の中から、</h3>
			<h3 class="kodawari-font">慧眼をもって最高の素材を選び抜く。</h3>
			<h3 class="kodawari-font">これが築地寿司のこだわりです。</h3>
		</div>
		<div class="col-xs-0 col-lg-6 kodawari-resp" id="box3">
			<div class="kodawari-image2"></div>
		</div>
	</div>
	<div class="row">
		<div class="col-xs-0 col-lg-6 kodawari-resp" id="box4">
			<div class="kodawari-image"></div>
		</div>
		<div class="col-xs-12 col-lg-6"style="padding:20px 0; text-align: center;">
			<h1 class="kodawari-font2"><%= image_tag 'logo.png',size:'40x40',class: 'kodawari-logo'%>握りのこだわり</h1>
			<h3 class="kodawari-font">すしは、味はもとより、見た目の美しさや握りの所作も、おいしさのひとつになります。</h3>
			<h3 class="kodawari-font">伝統的な江戸前スタイルに、アーティストともいえる繊細な職人技を加えて、ひとつひとつ愛情をこめて握る。</h3>
			<h3 class="kodawari-font">ネタ・シャリ・わさびの三位一体。お客様が口にされたときのバランスを考えて、温度・湿度・熟成には人一倍こだわってご提供いたします。</h3>
		</div>
	</div>
</div>

<!-- 画像動き -->
<script type="text/javascript">
$(function() {

	$("#box3").animate( { width: 'show' }, 2000 );
  	$("#box4").animate({ width: 'show' }, 2000 );
});
</script>

app/views/home/menus.html.erb
<div class="container background-image">
	<div class="row">
	    <div class="menus-title-image">
	      	<p class="menus-title-font">お品書き</p>
	    </div>
	    <nav>
			<ul class="nav-list">
				<li class="menus-nav-item col-xs-6 col-lg-3"><a href="#link1" id="menus-nav-font">おまかせコース</a></li>
				<li class="menus-nav-item col-xs-6 col-lg-3"><a href="#link2" id="menus-nav-font">握り寿司　巻物</a></li>
	 			<li class="menus-nav-item col-xs-6 col-lg-3"><a href="#link3" id="menus-nav-font">一品料理</a></li>
	 			<li class="menus-nav-item col-xs-6 col-lg-3"><a href="#link4" id="menus-nav-font">飲み物</a></li>
			</ul>
		</nav>
    </div>
	<div class="row ">
		<h1 class="menus-title" id="link1"><%= image_tag 'logo.png',size:'40x40',class: 'menus-logo'%>おまかせコース</h1>
		<div class="clearfix">
			<%= image_tag 'image2.jpg',class: 'menus-image1'%>
			<div class="menus-image4" style="text-align: center;">
				<h1 class="menus-font"><span class="border">おまかせコース(特上)</span></h1>
				<h1 class="menus-font2">20,000円(税別)</h1>
				<h4 class="menus-font">先付、小鉢２品、刺身５種、焼き物、揚げ物、 蒸し物、鮨１０貫、お椀、デザート</h4>
				<h1 class="menus-font"><span class="border">おまかせコース(上)</span></h1>
				<h1 class="menus-font2">15,000円(税別)</h1>
				<h4 class="menus-font">先付、小鉢２品、刺身３種、焼き物、揚げ物、 鮨８貫、お椀、デザート</h4>
			</div>
		</div>
		 <h1 class="menus-title" id="link2"><%= image_tag 'logo.png',size:'40x40',class: 'menus-logo'%>握り寿司　巻物</h1>
		<div class="clearfix">
			<div class="menus-image4 " style="text-align: center;">
				<h2 class="menus-font"><span class="border">握り寿司</span></h2>
				<h3>松（まつ） 5,000円(税別)</h3>
				<h3>竹（たけ） 3,000円(税別)</h3>
				<h3>梅（うめ） 2,000円(税別)</h3>
				<h4 class="menus-font">大とろ、うに、本みる貝、あわび、中とろ、赤身まぐろ、赤貝、煮はまぐり、えんがわ、赤貝、活海老、あなご、鯵、 すみいか、小柱、数の子、天然鯛、帆立、いくら、鯖、こはだ、玉子、等の旬の素材</h4>
				<h2 class="menus-font2"><span class="border">巻物</span></h2>
				<h4 class="menus-font2">ねぎとろ巻、とろ巻、あなきゅう巻、鉄火巻、いくら巻、梅しそ巻、納豆巻、のり巻、かっぱ巻、たくわん巻</h4>
			</div>
			<%= image_tag 'image3.jpg',class: 'menus-image1'%>
		</div>
		<h1 class="menus-title" id="link3"><%= image_tag 'logo.png',size:'40x40',class: 'menus-logo'%>一品料理</h1>
		<div class="menus-image2" style="text-align: center;">
			<div class="col-xs-12 col-lg-6">
				<h2 class="menus-font3"><span class="border">一品料理</span></h2>
				<h3>お新香盛合せ　　　　780円(税別)</h3>
				<h3>寿司屋のサラダ　　1,100円(税別)</h3>
				<h3>寿司屋の酢の物　　1,380円(税別)</h3>
				<h3>北海道風茶碗蒸し　　700円(税別)</h3>
				<h3>寿司屋の珍味　　　550円(税別)～<br>(内容はスタッフにお尋ねください)</h3>
				<h2 class="menus-font3"><span class="border">焼き物</span></h2>
				<%= image_tag 'image5.jpg',class: 'menus-image3'%>
				<h3>季節の焼物　　　　1,500円～(税別)<br>(内容はスタッフにお尋ねください)</h3>
				<h3>本ししゃも焼き（オス・1本)　　550円(税別)</h3>
				<h3>本ししゃも焼き（メス・1本）　　780円(税別)</h3>
				<h3>のどぐろ一夜干し　　1,500円(税別)</h3>
				<h2 class="menus-font3"><span class="border">デザート</span></h2>
				<h3>本日のデザート　　550円(税別)</h3>
				<h3>アイスクリーム　　420円(税別)</h3>
			</div>
			<div class="col-xs-12 col-lg-6">
				<h2 class="menus-font3"><span class="border">お造り盛り合わせ</span></h2>
				<%= image_tag 'image4.jpg',class: 'menus-image3'%>
				<h3>旬のお造り盛合せ　　　　2,500円(税別)<br>(1名様用)</h3>
				<h3>おまかせお造り盛合せ　　5,000円～(税別)<br>(人数に応じて対応させていただきます)</h3>
				<h3>貝尽くし盛合　　　　　3,500円(税別)</h3>
				<h2 class="menus-font3"><span class="border">小鉢</span></h2>
				<%= image_tag 'image6.jpg',class: 'menus-image3'%>
				<h3>小樽漁師風いかそうめん　1,380円(税別)</h3>
				<h3>海水うに小鉢　　　2,500円(税別)</h3>
				<h3>いくら小鉢　　　　2,100円(税別)</h3>
				<h3>大つぶ貝刺　　　　2,100円(税別)</h3>
			</div>
		</div>
		<h1 class="menus-title" id="link4"><%= image_tag 'logo.png',size:'40x40',class: 'menus-logo'%>飲み物</h1>
		<div class="clearfix">
			<%= image_tag 'image7.jpg',class: 'menus-image1'%>
			<div class="menus-image4" style="text-align: center;">
				<h2 class="menus-font4"><span class="border">日本酒</span></h2>
				<h4 class="menus-font4">江戸開城、獺祭、船中八策、土佐鶴、日高見・弥助、八海山純米吟醸、大那、伯楽星、新政No,6、田酒、黒龍</h4>
				<h2 class="menus-font4"><span class="border">焼酎</span></h2>
				<h4 class="menus-font4">吉四六、二階堂、中々、百年の孤独、魔王、富乃宝山、森伊蔵、村尾、獺祭、八海山よろしく千萬</h4>
				<h2 class="menus-font4"><span class="border">その他</span></h2>
				<h4 class="menus-font4">キリン一番搾り、スーパードライ　ノンアルコールビール、ハイボール　梅酒サワー　緑茶ハイ　烏龍ハイ　 レモンサワー</h4>
				<h2 class="menus-font4"><span class="border">ソフトドリンク</span></h2>
				<h4 class="menus-font4">緑茶　烏龍茶　コーラ　オレンジジュース　炭酸水</h4>
			</div>
		</div>
	</div>
	<div class="row" style="text-align: center;padding-top:10px;" >
		<span id="back">
		    <a href="#">
		      	<%= image_tag 'arrow.png'%>
		    </a>
		</span>
	</div>
</div>

<!-- トップに戻る -->
<script type="text/javascript">
  $(function(){

    $('#back a').on('click',function(){
    $('body, html').animate({
      scrollTop:0
    }, 800);
      return false;
  });
});
</script>

app/views/home/store.html.erb
<div class="container background-image">
	<div class="row">
	    <div class="store-title">
	      	<h1 class="store-title-font">店舗案内</h1>
	    </div>
    </div>
    <div class="row">
    	<div class="col-xs-0 col-lg-2"></div>
	    <div class="col-xs-12 col-lg-4 store-resp">
	    	<h3 class="store-font"><span class="border">住所</span></h3>
	    	<h4>〒150-0041<br>東京都渋谷区神南１丁目１９−１１ パークウェースクエア24階　<a href="https://goo.gl/maps/8cfDzHiNGJSxUL1CA">GoogleMap</a></h4>
	    	<h4 class="store-font">渋谷駅ハチ公前より徒歩7分</h4>
	    	<h3 class="store-font"><span class="border">電話番号</span></h3>
	    	<h4>000-0000-0000</h4>
	    	<h3 class="store-font"><span class="border">定休日</span></h3>
	    	<h4>毎週日曜日</h4>
	    </div>
	    <div class="col-xs-12 col-lg-4 store-resp">
	    	<h3 class="store-font"><span class="border">営業時間</span></h3>
	    	<h4>ランチ<br>11：00～15：00（L.O 14：30）</h4>
	    	<h4>ディナー<br>17：00～22：00（L.O 21：30）</h4>
	    	<h3 class="store-font"><span class="border">座席数</span></h3>
	    	<h4>カウンター 10席（貸切可）</h4>
	    </div>
	    <div class="col-xs-0 col-lg-2"></div>
    </div>
    <div class="row">
    	<div class="col-xs-0 col-lg-2"></div>
    	<div class="col-xs-11 col-lg-8">
    		<div id="map" class="store-map"></div>
    	</div>
    	<div class="col-xs-1 col-lg-2"></div>
    </div>
</div>
<!-- 地図 -->
<script>
    function initMap() {
    	// 住所を指定する
	    var opts = {
	        zoom: 15,
	        center: new google.maps.LatLng(35.662804,139.699474)
      	};
      	// 地図を表示する
      	var map = new google.maps.Map(document.getElementById("map"), opts);
      	// マーカーの住所を指定する
      	var latlng = new google.maps.LatLng(35.662804,139.699474);
      	// マーカーを置く
		new google.maps.Marker({
		  position: latlng,
		  map: map
		});
    }
</script>



<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['KEY'] %>&callback=initMap" async defer></script>

app/views/home/top.html.erb
<body class="top-start">
	<div class="top-title">
		<!-- スキッパー -->
		<div class="theTarget">
			<%= image_tag 'top-image.jpg'%>
			<%= image_tag 'top-image2.jpg'%>
			<%= image_tag 'top-image3.jpg'%>
			<%= image_tag 'top-image4.jpg'%>
			<%= image_tag 'top-image5.jpg'%>
		</div>
	</div>
	<div class="container background-image">
		<div class="row">
			<div class="col-xs-12 col-lg-4" style="padding: 0; padding-top: 30px;">
				<%= link_to menus_path(anchor:"link1"),class: 'top-menu-links' do %>
					<div class="top-menus-image1">
						<p class="top-menus-font">おまかせコース</p>
					</div>
				<% end %>
				<%= link_to menus_path(anchor:"link3"),class: 'top-menu-links' do %>
					<div class="top-menus-image2">
						<p class="top-menus-font">一品料理</p>
					</div>
				<% end %>
			</div>
			<div class="col-xs-12 col-lg-4 top-menus-resp">
				<%= link_to menus_path(anchor:"link2"),class: 'top-menu-links' do %>
					<div class="top-menus-image3">
						<p class="top-menus-font">握り寿司　巻物</p>
					</div>
				<% end %>
				<%= link_to menus_path(anchor:"link4"),class: 'top-menu-links' do %>
					<div class="top-menus-image4">
						<p class="top-menus-font">飲み物</p>
					</div>
				<% end %>
			</div>
			<div class="col-xs-12 col-lg-4">
				<h2 class="top-notice-font"><span class= "border">お知らせ</span></h2>
				<div class="top-notices-background">
					<table class="table table-bordered">
			            <tbody>
			              <% @notices.each do |notice| %>
			              <tr>
			                <td>
			                  <p class="top-notice-font2"><%= notice.created_at.strftime("%Y/%m/%d") %>
			                  <%= link_to notice_path(notice.id),class: 'top-notice-link' do %>
			                    <%= "◆"+ notice.title%>
			                  <% end %>
			                  </p>
			                </td>
			              </tr>
			              <% end %>
			            </tbody>
			        </table>
			        <%= link_to notices_path,class: "top-notice-link2 pull-right" do %>
			        	お知らせ一覧はこちらから
			        <% end %>
			    </div>
			</div>
		</div>
		<div class="row" style = "padding-top: 30px;">
			<div class="top-store_title"></div>
			<h2 class="top-store-font"><span class="border">店舗案内</span></h2>
			<div class="col-xs-12 col-lg-6 top-menus-resp2">
				<p class="top-store-font2"><span class="border">店名</span></p>
				<p class="top-store-font2">築地寿司</p>
				<p class="top-store-font2"><span class="border">住所</span></p>
				<p class="top-store-font2">東京都渋谷区神南１丁目１９−１１<br>パークウェースクエア24階</p>
				<p class="top-store-font2"><span class="border">電話番号</span></p>
				<p class="top-store-font2">000-0000-0000</p>
			</div>
			<div class="col-xs-12 col-lg-6 top-menus-resp2">
				<div class="top-menus-resp3"id="map"></div>
			</div>
		</div>
		<div class="row" style="text-align: center;" >
			<span id="back">
			    <a href="#">
			      	<%= image_tag 'arrow.png'%>
			    </a>
			</span>
		</div>
	</div>
</body>
<!-- メニュー画像とトップに戻る -->
<script type="text/javascript">
$(function(){
	setTimeout(function(){
    $('.top-start').removeClass('top-start');
  },3000);
});
$(function(){
    $('.top-menus-font').mouseover(function(){
        $(this).addClass('top-menus-image5');
    });
    $('.top-menus-font').mouseout(function(){
        $(this).removeClass('top-menus-image5');
    });

    $('#back a').on('click',function(){
    $('body, html').animate({
      scrollTop:0
    }, 800);
      return false;
  });
});
</script>
<!-- 地図 -->
<script>
    function initMap() {
    	// 住所を指定する
	    var opts = {
	        zoom: 15,
	        center: new google.maps.LatLng(35.662804,139.699474)
      	};
      	// 地図を表示する
      	var map = new google.maps.Map(document.getElementById("map"), opts);
      	// マーカーの住所を指定する
      	var latlng = new google.maps.LatLng(35.662804,139.699474);
      	// マーカーを置く
		new google.maps.Marker({
		  position: latlng,
		  map: map
		});
    }
</script>

<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['KEY'] %>&callback=initMap" async defer></script>