config/routes.rb
Rails.application.routes.draw do

	#HP側
	root to: "home#top"
	get "about" => "home#about"
	get "kodawari" => "home#kodawari"
	get "store" => "home#store"
	get "menus" => "home#menus"
	resources :notices, only: [:index,:show]
	resources :reservations, only: [:show,:create,:new,:destroy]
	post "/reservations/confirm"  => "reservations#confirm"
	post "/reservations/new"=> "reservations#back"
	get "delete"=> "reservations#delete"
	get 'ajax', to: 'reservations#ajax'

	 ##管理者側
  	devise_for :admins, skip: :all
  	#ログイン画面制限
	devise_scope :admin do
	  get 'login' => 'devise/sessions#new', as: :new_admin_session
	  post 'login' => 'devise/sessions#create', as: :admin_session
	  delete 'logout' => 'devise/sessions#destroy', as: :destroy_admin_session
	end

	# ゲストログイン用URL
	devise_scope :admin do
	    post 'admins/guest_sign_in', to: 'admins/sessions#new_guest'
	end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	namespace :admin do
	  resources :notices
	  resources :reservations
	  get 'ajax', to: 'reservations#ajax'
	  root to: "home#about"
	end
end

app/models/notice.rb
class Notice < ApplicationRecord

	attachment :image
	validates :title, presence: true
	validates :content, length: {maximum: 200}

	#お知らせ詳細の前後の投稿リンク
	def previous
	    Notice.where("id < ?",id).order("id DESC").first
	end
	def next
	    Notice.where("id > ?", id).order("id ASC").first
	end
end

app/controllers/admin/notices_controller.rb
class Admin::NoticesController < ApplicationController

	before_action :authenticate_admin!

	before_action :find_notice, only: [:show,:edit,:destroy,:update]

	def index
		@notices = Notice.order(created_at: :desc).page(params[:page]).per(8)
	end

	def new
		@notice = Notice.new
	end

	def create
		@notice = Notice.new(notice_params)
		if @notice.save #入力されたデータをdbに保存する。
	      redirect_to admin_notices_path
	    else
	      render 'new'
	    end
	end

	def show
	end

	def edit
	end

	def update
		if @notice.update(notice_params)
			redirect_to admin_notice_path(@notice.id)
		else
			render 'edit'
		end
	end

	def destroy
		@notice.destroy
    	redirect_to admin_notices_path
	end

	private

	def notice_params
	    params.require(:notice).permit(:image,:title,:content)
	end

	def find_notice
		@notice = Notice.find(params[:id])
	end
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController

	def index
		@notices = Notice.order(created_at: :desc).page(params[:page]).per(4)
	end

	def show
		@notice = Notice.find(params[:id])
	end

end

app/views/admin/notices/edit.html.erb
<div class="container-fluid background-image2">
  <div class="row">
    <h2 class="notice-font3"><span class="border">お知らせ編集</span></h2>
    <div class="col-xs-3"></div>
      <div class="col-xs-6"style="padding-bottom: 20px;">
      <%= form_for(@notice, url:admin_notice_path(@notice.id)) do |f| %>
        <% if @notice.errors.any? %>
          <div id="error_explanation">
            <font color = "red">
              <h3>入力した内容に<%= @notice.errors.count %>件のエラーがあります</h3>
              <ul>
              <% @notice.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </font>
          </div>
        <% end %>
        <div class="col-xs-5">
          <div class="field row">
            <h4>　画像</h4>
            <% if @notice.image.present? %>
              <%= attachment_image_tag @notice, :image, id: :img_prev, size:'200x200' %>
            <% else %>
              <%= image_tag "no_image.jpg", id: :img_prev, size:'200x200' %>
            <% end %>
            <%= f.attachment_field :image, id: :notice_img %>
          </div>
        </div>
        <div class="col-xs-7">
          <div class="field row">
            <h4>タイトル</h4>
            <%= f.text_field :title,style: "width:100%; color: black;" %>
          </div>
          <div class="field row">
            <h4>　内容</h4>
            <%= f.text_area :content,style: "width:100%; color: black;",rows:"10" %>
          </div>
          <div class="btn-group btn-group-justified">
            <div class="btn-group">
              <%= f.submit "編集完了", class: "btn btn-warning" %>
            </div>
            <div class="btn-group">
              <%= link_to admin_notice_path(@notice.id) do %>
                <button class="btn btn-success">詳細に戻る</button>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
      </div>
    <div class="col-xs-3"></div>
  </div>
</div>

<!-- 投稿画像を選択した時に、投稿画像を読み込み＆反映 -->
<script type="text/javascript">
  $(function(){
    function readURL(input){
      if(input.files && input.files[0]){
        var reader = new FileReader();
        reader.onload = function(e){
          $('#img_prev').attr('src',e.target.result);
        }
        reader.readAsDataURL(input.files[0]);
      }
    }
    $("#notice_img").change(function(){
      readURL(this);
    });
  });
</script>

app/views/admin/notices/index.html.erb
<div class="container-fluid background-image2">
  <div class="row">
    <div class="col-xs-3"></div>
    <div class="col-xs-6">
      <h2 style="text-align: center;"><span class ="border">お知らせ</span></h2>
      <div class="pull-right">
        <%= link_to new_admin_notice_path do %>
          <button class="btn btn-primary">お知らせ投稿</button>
        <% end %>
      </div>
    </div>
    <div class="col-xs-3"></div>
  </div>
  <div class="row">
    <div class="col-xs-3"></div>
      <div class="col-xs-6"style="padding-top: 20px">
        <table class="table notice-table">
          <tbody>
            <% @notices.each do |notice| %>
            <tr>
              <td width="30%">
                <a><%= attachment_image_tag notice, :image, fallback: "no_image.jpg", size:'200x200' %></a>
              </td>
              <td width="60%">
                <p class="notice-font2"><%= notice.created_at.strftime("%Y/%m/%d") %>
                <%= link_to admin_notice_path(notice.id), class: "notice-font" do %>
                  <%= "◆" + notice.title.truncate(20)%>
                <% end %>
                </p>
                <h3 class="notice-font5">
                  <%= notice.content.truncate(80) %>
                </h3>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
        <div  class="kaminari">
          <%= paginate @notices %>
        </div>
      </div>
    <div class="col-xs-3"></div>
  </div>
</div>

app/views/admin/notices/new.html.erb
<div class="container-fluid background-image2">
  <div class="row">
    <h2 class="notice-font3"><span class="border">お知らせ投稿</span></h2>
    <div class="col-xs-3"></div>
      <div class="col-xs-6"style="padding-bottom: 20px;">
      <%= form_for(@notice, url:admin_notices_path) do |f| %>
        <% if @notice.errors.any? %>
          <div id="error_explanation">
            <font color = "red">
              <h3>入力した内容に<%= @notice.errors.count %>件のエラーがあります</h3>
              <ul>
              <% @notice.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </font>
          </div>
        <% end %>
        <div class="col-xs-5">
          <h4>　画像</h4>
          <!-- 投稿画像がある場合とない場合とで表示を分岐 -->
          <% if @notice.image.present? %>
            <%= attachment_image_tag @notice, :image, id: :img_prev, size:'200x200' %>
          <% else %>
            <%= image_tag "no_image.jpg", id: :img_prev, size:'200x200' %>
          <% end %>
          <div class="field row">
            <%= f.attachment_field :image, id: :notice_img %>
          </div>
        </div>
        <div class="col-xs-7">
          <div class="field row">
            <h4>タイトル</h4>
            <%= f.text_field :title,style: "width:100%; color: black;"%>
          </div>
          <div class="field row">
            <h4>　内容</h4>
            <%= f.text_area :content,style: "width:100%; color: black;",rows:"10"%>
          </div>
          <div class="btn-group btn-group-justified">
            <div class="btn-group">
              <%= f.submit "投稿する", class: "btn btn-primary" %>
            </div>
            <div class="btn-group">
              <%= link_to admin_notices_path,method: :get do %>
                <button class="btn btn-default">一覧に戻る</button>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
      </div>
    <div class="col-xs-3"></div>
  </div>
</div>

<!-- 投稿画像を選択した時に、投稿画像を読み込み＆反映 -->
<script type="text/javascript">
  $(function(){
    function readURL(input){
      if(input.files && input.files[0]){
        var reader = new FileReader();
        reader.onload = function(e){
          $('#img_prev').attr('src',e.target.result);
        }
        reader.readAsDataURL(input.files[0]);
      }
    }
    $("#notice_img").change(function(){
      readURL(this);
    });
  });
</script>

app/views/admin/notices/show.html.erb
<div class="container-fluid background-image2">
  <div class="row">
    <h2 class="notice-font3"><span class="border">お知らせ詳細</span></h2>
    <div class="col-xs-3"></div>
      <div class="col-xs-6">
        <h3 style="text-align: center;"><%= @notice.created_at.strftime("%Y/%m/%d")%></h3>
        <h1 class="notice-font4"><%= @notice.title %></h1>
        <div class="col-xs-4" style="text-align: right;">
          <span><%= attachment_image_tag @notice, :image, fallback: "no_image.jpg", size:'200x200'%></span>
        </div>
        <div class="col-xs-8">
          <h4 class="notice-font5"><%= @notice.content %></h4>
          <div class="btn-group btn-group-justified" >
            <div class="btn-group">
              <%= link_to edit_admin_notice_path(@notice.id) do %>
                <button class="btn btn-warning">編集する</button>
              <% end %>
            </div>
            <div class="btn-group">
              <%= link_to admin_notices_path do %>
                <button class="btn btn-default">一覧に戻る</button>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <div class="col-xs-3"></div>
  </div>
  <div class="row">
    <div class="col-xs-6 notice-link2">
      <% if @notice.previous.present? %>
        <%= link_to admin_notice_path(@notice.previous.id), class: 'notice-link4' do %>
          <%= "<<　" + @notice.previous.title + "　|" %>
        <% end %>
      <% end %>
    </div>
    <div class="col-xs-6 notice-link3">
      <% if @notice.next.present? %>
        <%= link_to admin_notice_path(@notice.next), class: 'notice-link4' do %>
          <%= "|　" + @notice.next.title + "　>>"  %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>