config/routes.rb
Rails.application.routes.draw do

	#HP側
	root to: "home#top"
	get "about" => "home#about"
	get "kodawari" => "home#kodawari"
	get "store" => "home#store"
	get "menus" => "home#menus"
	resources :notices, only: [:index,:show]
	resources :reservations, only: [:show,:create,:new,:destroy]
	post "/reservations/confirm"  => "reservations#confirm"
	post "/reservations/new"=> "reservations#back"
	get "delete"=> "reservations#delete"
	get 'ajax', to: 'reservations#ajax'

	 ##管理者側
  	devise_for :admins, skip: :all
  	#ログイン画面制限
	devise_scope :admin do
	  get 'login' => 'devise/sessions#new', as: :new_admin_session
	  post 'login' => 'devise/sessions#create', as: :admin_session
	  delete 'logout' => 'devise/sessions#destroy', as: :destroy_admin_session
	end

	# ゲストログイン用URL
	devise_scope :admin do
	    post 'admins/guest_sign_in', to: 'admins/sessions#new_guest'
	end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	namespace :admin do
	  resources :notices
	  resources :reservations
	  get 'ajax', to: 'reservations#ajax'
	  root to: "home#about"
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SushiHp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <header class="navbar">
      <div class="container">
        <div class= "flex">
          <i class="flex-item"></i>
            <div class="nav-logo">
              <% if admin_signed_in? %>
                <%= link_to admin_root_path do %>
                  <%= image_tag 'sushi.png', size: "200x70" %>
                <% end %>
              <% else %>
                <%= link_to root_path do %>
                  <%= image_tag 'sushi.png', size: "200x70" %>
                <% end %>
              <% end %>
            </div>
              <div id="nav-drawer">
                <input id="nav-input" type="checkbox" class="nav-unshown">
                <label id="nav-open" for="nav-input"><span></span></label>
                <label class="nav-unshown" id="nav-close" for="nav-input"></label>
              <div id="nav-content">
                <% if admin_signed_in? %>
                  <p class = "nav-item" style = "padding-top: 20px"><a href="/admin" class= "nav-font">サイトの使い方</a></p>
                  <p class = "nav-item"><a href="/admin/notices" class= "nav-font" >お知らせ</a></p>
                  <p class = "nav-item"><a href="/admin/reservations" class= "nav-font">予約</a></p>
                  <p class = "nav-item"><a href="/logout" class= "nav-font" data-method="delete">ログアウト</a></p>
                <% else %>
                  <p class = "nav-item"><a href="/notices" class= "nav-font">お知らせ</a></p>
                  <p class = "nav-item"><a href="/kodawari" class= "nav-font">こだわり</a></p>
                  <p class = "nav-item"><a href="/menus" class= "nav-font">お品書き</a></p>
                  <p class = "nav-item"><a href="/store" class= "nav-font">店舗案内</a></p>
                  <p class = "nav-item"><a href="/about" class= "nav-font">予約機能の使い方</a></p>
                  <p class = "nav-item"><a href="/reservations/new" class= "nav-font">予約</a></p>
                  <p class = "nav-item2"><a href="/login" class= "nav-font">管理者</a></p>
                <% end %>
              </div>
            </div>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer>
      <div class = "footer">
        <%= image_tag 'sushi.png', size: "200x75" ,class: "footer-logo"%>
        <p class= "footer-font">東京都渋谷区神南１丁目１９−１１ パークウェースクエア24階</p>
        <p class= "footer-font">000-0000-0000</p>
      </div>
    </footer>
  </body>
</html>

<!-- ハンバーガーメニュー -->
<script type="text/javascript">
  $(function(){
    $('.nav-font').mouseover(function(){
        $(this).css({'color': '#ffffff'});
        $(this).css({'font-size': '20px'});
        $(this).css({'text-decoration': 'none'});
    });
    $('.nav-font').mouseout(function(){
        $(this).css({'font-size': '15px'});
    });
});
</script>